#!/usr/bin/env bash
# Simple bash script that output the content
# of the file ``/etc/passwd`` showing only:
# - username.
# - user id.
# - Home directory path for the user.

file="/etc/passwd"

while IFS=":" read -r -a array
do
	echo "${array[0]}:${array[2]}:${array[6]}"
done < "$file"
